In [1]:
import numpy as np

#### Reverse a vector (first element becomes last) (★☆☆)
`hint: arange`

In [2]:
Z = np.arange(50)
Z = Z[::-1]
print(Z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


#### Create a 3x3 identity matrix (★☆☆)
`hint: np.eye`

In [3]:
Z = np.eye(3)
print(Z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)
`hint: np.diag`

In [4]:
Z = np.diag(1+np.arange(4),k=-1)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### Normalize a 5x5 random matrix (★☆☆)
`hint: (x -mean)/std`

In [5]:
Z = np.random.random((5,5))
Z = (Z - np.mean (Z)) / (np.std (Z))
print(Z)

[[-1.15525405 -1.12709474 -0.64883782  1.7141042   1.5203693 ]
 [-0.47166085 -0.7117492   0.66661473  1.14354236  0.42119043]
 [ 0.95884762 -0.79221324  0.49961338  0.52138595 -0.44744947]
 [-0.84616279  1.13102969 -1.05328755 -0.82281896  1.25468812]
 [-1.33372787  1.72581748 -0.40547958 -0.91106192 -0.83040521]]


#### Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)


In [6]:
Z = np.dot(np.ones((5,3)), np.ones((3,2)))
print(Z)

# Alternative solution, in Python 3.5 and above
Z = np.ones((5,3)) @ np.ones((3,2))
print(Z)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]
[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


#### Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```
`hint: imaginary number`

In [7]:
np.sqrt(-1) == np.emath.sqrt(-1)

/var/folders/tg/p63f4kmn1fz2m94_k3h13byh0000gn/T/ipykernel_23673/244602691.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


False

#### How to get all the dates corresponding to the month of July 2016? (★★☆)
`hint: np.arange(dtype=datetime64['D'])`

In [10]:
Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)
`hint: %, np.floor, astype, np.trunc`

In [12]:
Z = np.random.uniform(0,10,10)

print(Z)
print(Z - Z%1)
print(Z // 1)
print(np.floor(Z))
print(Z.astype(int))
print(np.trunc(Z))

[7.35188405 9.14893513 8.37398332 3.89948379 0.87535612 2.53026514
 0.03460699 9.1315277  9.16602638 4.43348685]
[7. 9. 8. 3. 0. 2. 0. 9. 9. 4.]
[7. 9. 8. 3. 0. 2. 0. 9. 9. 4.]
[7. 9. 8. 3. 0. 2. 0. 9. 9. 4.]
[7 9 8 3 0 2 0 9 9 4]
[7. 9. 8. 3. 0. 2. 0. 9. 9. 4.]


#### Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)
`hint: np.linspace`

In [13]:
Z = np.linspace(0,1,11,endpoint=False)[1:]
print(Z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### Create a random vector of size 10 and sort it (★★☆)
`hint: sort`

In [14]:
Z = np.random.random(10)
Z.sort()
print(Z)

[0.12480894 0.20923173 0.24536085 0.27875242 0.56631657 0.68031519
 0.72584428 0.76966361 0.78640104 0.95436628]


#### How to sum a small array faster than np.sum? (★★☆)
`hint: np.add.reduce`

In [15]:
Z = np.arange(10)
np.add.reduce(Z)

45

#### How to sort an array by the nth column? (★★☆)
`hint: argsort`

In [17]:
Z = np.random.randint(0,10,(3,3))
print(Z)
print(Z[Z[:,1].argsort()])

[[7 5 0]
 [7 8 5]
 [4 4 5]]
[[4 4 5]
 [7 5 0]
 [7 8 5]]


#### Find the nearest value from a given value in an array (★★☆)
`hint: np.abs, argmin, flat`

In [18]:
Z = np.random.uniform(0,1,10)
z = 0.5
m = Z.flat[np.abs(Z - z).argmin()]
print(m)

0.5091601602021641


#### Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)
`hint: array[::4]`

In [19]:
Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print(Z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### How to swap two rows of an array? (★★★)
`hint: array[[]] = array[[]]`

In [20]:
A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]
print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### How to negate a boolean, or to change the sign of a float inplace? (★★★)
`hint: np.logical_not, np.negative`

In [21]:
Z = np.random.randint(0,2,100)
np.logical_not(Z, out=Z)

Z = np.random.uniform(-1.0,1.0,100)
np.negative(Z, out=Z)

array([-0.36648498,  0.01260152,  0.03234153,  0.35676798, -0.53441777,
       -0.85324975,  0.27602309,  0.29007048, -0.35459407,  0.50994057,
       -0.17181759,  0.20364261, -0.25246316,  0.37154989, -0.84294092,
       -0.59640696,  0.5296306 ,  0.2127239 , -0.33687796,  0.54814066,
        0.48360999, -0.1196864 ,  0.02006802, -0.95626743, -0.1391711 ,
        0.66840129, -0.09871358,  0.82110484,  0.28732146, -0.39649319,
       -0.50471674, -0.80102395,  0.87900392,  0.31708407, -0.76064033,
        0.33157074,  0.65002072, -0.63114039, -0.8201895 , -0.44922698,
       -0.454979  , -0.43765571, -0.80538886,  0.4423745 , -0.64341987,
       -0.62636469,  0.04842413, -0.42840025, -0.0424759 ,  0.05591455,
       -0.62925651, -0.75758847, -0.1453749 , -0.03726975,  0.9148915 ,
       -0.8972695 , -0.36502652,  0.21402873, -0.30817487, -0.38550801,
       -0.16650447,  0.44701657, -0.43132209,  0.05707792, -0.82771765,
        0.88515066, -0.78280561,  0.64656372,  0.73319078, -0.30

#### Compute a matrix rank (★★★)
`hint: np.linalg.svd, np.linalg.matrix_rank`

In [23]:
Z = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(Z) # Singular Value Decomposition
rank = np.sum(S > 1e-10)
print(rank)

rank = np.linalg.matrix_rank(Z)
print(rank)

10
10


#### How to get the n largest values of an array (★★★)
`hint: np.argsort | np.argpartition`

In [24]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5

# Slow
print (Z[np.argsort(Z)[-n:]])

# Fast
print (Z[np.argpartition(-Z,n)[:n]])

[9995 9996 9997 9998 9999]
[9999 9995 9997 9998 9996]


#### Given a two dimensional array, how to extract unique rows? (★★★)
`hint: np.ascontiguousarray | np.unique`

In [26]:
Z = np.random.randint(0,2,(6,3))
uZ = np.unique(Z, axis=0)
print(uZ)

[[0 0 0]
 [0 0 1]
 [0 1 1]
 [1 1 0]]
